version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    volumes:
      - ./server/src:/app/server/src
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    depends_on:
      - server
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    restart: always
  db:
    image: mongo
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: